### ISSUE TITLE
Uncaught Error: spawn julia ENOENT

### ISSUE THREAD

**Issue by ssfrr** [vindvaki/atom-autocomplete-julia#3]
I have julia available in `/usr/local/bin`, which isn't in `$PATH` by unless I run Atom from a shell session. I tried adding `/usr/local/bin/` to `process.env.PATH` in `init.coffee`, and I can see from the console that it's getting added, but I still get this error when autocomplete-julia tries to launch the julia process. Apparently `init.coffee` is run after packages are loaded. Would it be possible to defer attempting to launch the julia process until after `init.coffee` is loaded?

**Comment by vindvaki** [comment]
@ssfrr Thanks for the report! 

I will investigate if there is any way to spawn the process until after `init.coffee` is loaded. 

Alternatively, we could let the user configure which `julia` they would like to use, because besides non-standard paths, they might want to use one that is not in the path at all.

In the meantime, you could try reloading the plugin after setting the path in `init.coffee`, because this would dispose of the current process and spawn a new one:

``` coffeescript
autocomplete_julia = atom.packages.getActivePackage("autocomplete-julia")
autocomplete_julia.disable()
autocomplete_julia.enable()
```

**Comment by vindvaki** [comment]
@ssfrr I just updated the package with the a configurable path for julia, since that seemed like an all around better solution. I'm closing this issue for now.

**Comment by ssfrr** [comment]
One issue is that when you try to edit it from the preferences pane it tries to re-spawn as you're typing in the path, so it keeps popping up errors.

Other than that I think this solution is good though, just a minor annoyance.

**Comment by vindvaki** [comment]
Yes, I should probably try to increase the the delay in the config change
listener, because it is quite annoying right now :)
